[package]
name = "tinynf"
version = "1.0.0"
edition = "2021"

[features]
constgenerics = []

[dependencies]
libc = "0.2.97"
memmap = "0.7.0"
x86_64 = { version = "0.14.3", default-features = false, features = ["instructions", "external_asm"] }
non-empty-vec = "0.2.3"

[profile.release]
lto = true
