[package]
name = "tinynf"
version = "1.0.0"
edition = "2021"

[features]
constgenerics = []

[dependencies]
libc = "0.2.119"
memmap = "0.7.0"
x86_64 = { version = "0.14.8", default-features = false, features = ["instructions", "external_asm"] }

[profile.release]
lto = true
debug = true
